name: calci
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  get_storage: ^2.0.3
  math_expressions: ^2.3.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.16
  flutter_test: 
    sdk: flutter
  very_good_analysis: ^3.1.0

flutter_native_splash:
  color: "#010101"


flutter:
  uses-material-design: true

